### ISSUE TITLE
User Authentication site: SMTP custom namespaces don't work on station.locomotive.works

### ISSUE THREAD

**Issue by greyskin** [locomotivecms/site-templates#7]
Steps to reproduce this issue:

### Part 1 - Test Default SMTP Namespace
1. Download a copy of the `auth` folder (User Authentication site)
2. Enter SMTP info under SMTP namespace in config/site.yml (i.e. address, port, user_name, password)
3. Create an user content_entry in data/accounts.yml
4. Deploy to station.locomotive.works with data (-d)
5. Visit the Reset Password page (reset_password.liquid) and enter email address of user created in step 3
6. Check email account and confirm receipt of password_reset_instructions email

### Part 2 - Set Up & Test Custom SMTP Namespace
7. Create a custom SMTP namespace and custom fields in metafields_schema.yml, e.g.
```
smtp_settings:
  label: Outgoing Email
  fields:

    server:
      label: SMTP Server
      type: string

    username:
      label: Username
      type: string

    password:
      label: Password
      type: string

    port:
      label: Port
      type: string
```
8. Add SMTP info under custom SMTP namespace in config/site.yml, e.g.
```
  smtp_settings:
    server: [same address used in Part 1]
    username: [same username used in Part 1]
    password: [same password used in Part 1]
    port: [same port used in Part 1]
```
9. Add fields to allow custom SMTP namespace on reset_password.liquid as per [Locomotive CMS documentation](https://doc.locomotivecms.com/docs/actions#forgot-password), e.g.
```
<input type="hidden" name="auth_email_smtp_namespace" value="smtp_settings">
<input type="hidden" name="auth_email_smtp_address_alias" value="server">
<input type="hidden" name="auth_email_smtp_port_alias" value="port">
<input type="hidden" name="auth_email_smtp_user_name_alias" value="username">
<input type="hidden" name="auth_email_smtp_password_alias" value="password">
```
10. Deploy to station.locomotive.works with data (-d)
11. Visit the Reset Password page (reset_password.liquid) and enter email address of user created in step 3 (the page alert will report successful email sending)
12. Check email account and confirm ***non***-receipt of password_reset_instructions email
